env: minikube
namespace: minikube

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: securemessages

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "300Mi"
      cpu: "150m"
    limits:
      memory: "375Mi"
      cpu: "300m"
  proxy:
    requests:
      memory: "64Mi"
      cpu: "30m"
    limits:
      memory: "128Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 200
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

dns:
  enabled: false
  wellKnownPort: 8080
